import {dot,normalize,softmax} from './engine.js';
const $=id=>document.getElementById(id),toyU=[[1,0],[0,1],[-.6,.8]],toyV=[[.8,.6],[0,1],[-.8,.6]];
const photos=['newfoundland_31.jpg','Persian_98.jpg','pug_57.jpg'],names=['Newfoundland','Persian cat','pug'];
let U=toyU,V=toyV,C=[],axis='row',i=0,j=0,stage=0,real=false,worker=null,live=null,gpu=null,runtime='JavaScript CPU';
function calculate(){const alpha=+$('alpha').value,S=C.map(r=>r.map(c=>alpha*c)),row=S.map(softmax),col=S[0].map((_,j)=>softmax(S.map(r=>r[j]))),li=-row.reduce((s,r,i)=>s+Math.log(r[i]),0)/3,lt=-col.reduce((s,r,i)=>s+Math.log(r[i]),0)/3;return{alpha,S,row,col,li,lt,loss:(li+lt)/2};}
function matrix(){const f=calculate(),selected=axis==='row'?i:j;let html='<span></span>'+names.map(n=>`<div class="col-label">a photo of a ${n}</div>`).join('');
for(let r=0;r<3;r++){html+=`<div class="row-label"><img src="images/${photos[r]}" alt="${names[r]}"><span>I${r+1} · ${names[r]}</span></div>`;for(let c=0;c<3;c++){let x=stage===0?C[r][c]:stage===1?f.S[r][c]:stage<4?Math.exp(f.S[r][c]-Math.max(...(axis==='row'?f.S[r]:f.S.map(a=>a[c])))):axis==='row'?f.row[r][c]:f.col[c][r];html+=`<button class="cell ${r===c?'paired':''} ${r===i&&c===j?'selected':''} ${(axis==='row'?r:c)===selected?'choice-'+axis:''}" data-r="${r}" data-c="${c}" aria-label="Image ${r+1}, caption ${c+1}: ${x.toFixed(4)}">${x.toFixed(4)}</button>`;}}
$('matrix').innerHTML=html;document.querySelectorAll('.cell').forEach(b=>b.onclick=()=>{i=+b.dataset.r;j=+b.dataset.c;render();});}
const fmt=x=>Number(x).toFixed(6),list=a=>'['+a.map(x=>Number(x).toFixed(4)).join(', ')+']';
function render(){if(!C.length)return;const f=calculate(),n=axis==='row'?i:j,choice=axis==='row'?j:i,s=axis==='row'?f.S[i]:f.S.map(r=>r[j]),mx=Math.max(...s),w=s.map(x=>Math.exp(x-mx)),z=w.reduce((a,b)=>a+b,0),p=softmax(s),paired=p[n];matrix();$('row').setAttribute('aria-pressed',axis==='row');$('col').setAttribute('aria-pressed',axis==='col');$('alpha-value').textContent=f.alpha.toFixed(1);$('tau').textContent='τ = 1/α = '+(1/f.alpha).toFixed(3);$('pair-label').textContent=`Selected I${i+1}, T${j+1}. ${axis==='row'?'Image '+(i+1)+' fixed; captions vary.':'Caption '+(j+1)+' fixed; images vary.'}`;
const titles=['Multiply coordinates and add','Scale the cosine','Make positive weights','Add the weights in this choice','Divide each weight by the sum','Penalize the observed partner','Average both matching directions'];$('operation').textContent=titles[stage];
let args='',calc='',take='';
if(stage===0){args=real?'512 normalized coordinates in each vector.':`u${i+1} = ${list(U[i])}; v${j+1} = ${list(V[j])}`;calc=real?`u${i+1} · v${j+1} = ${fmt(C[i][j])}`:`(${U[i][0]} × ${V[j][0]}) + (${U[i][1]} × ${V[j][1]}) = ${fmt(C[i][j])}`;take='Cosine describes direction. It is not a probability.';}
if(stage===1){args=`cosine = ${fmt(C[i][j])}; α = ${f.alpha}`;calc=`S${i+1}${j+1} = ${f.alpha} × ${fmt(C[i][j])} = ${fmt(f.S[i][j])}`;take='The ranking is unchanged. The scale controls how sharply softmax will separate the choices.';}
if(stage===2){args=`Selected logits: ${list(s)}. Subtract max ${fmt(mx)} for stable softmax.`;calc=`exp(${list(s.map(x=>x-mx))}) = ${list(w)}`;take='A shared shift cancels when we divide by the sum. All weights are positive.';}
if(stage===3){args=`${axis==='row'?'Row':'Column'} ${n+1} weights: ${list(w)}`;calc=`Z = ${w.map(fmt).join(' + ')} = ${fmt(z)}`;take='Every entry in this one choice uses the same denominator.';}
if(stage===4){args=`Pair weight ${fmt(w[choice])}; ${axis} sum ${fmt(z)}`;calc=`${fmt(w[choice])} / ${fmt(z)} = ${fmt(p[choice])}\n${(100*p[choice]).toFixed(2)}% of this menu`;take='The shares sum to 1 in this direction. They depend on all supplied candidates.';}
if(stage===5){args=`Observed partner is diagonal pair ${n+1}. Target share = ${fmt(paired)}.`;calc=`−ln(${fmt(paired)}) = ${fmt(-Math.log(paired))}`;take='A smaller share for the paired record gives a larger penalty. This inspects the objective; it does not update the model.';}
if(stage===6){args=`Image → text mean: ${fmt(f.li)}\nText → image mean: ${fmt(f.lt)}`;calc=`(${fmt(f.li)} + ${fmt(f.lt)}) / 2 = ${fmt(f.loss)}`;take='This scalar supplies the training signal for both branches. The notebook shows the backward and optimizer steps.';}
$('arguments').textContent=args;$('calculation').innerText=calc;$('takeaway').textContent=take;$('previous').disabled=stage===0;$('next').disabled=stage===6;$('stage').value=stage;$('vector-note').textContent=real?'Measured 512D normalized outputs. Only eight coordinates are previewed below.':'Chosen 2D unit vectors. Photo labels maintain continuity with the lecture.';$('vectors').textContent=JSON.stringify({U:U.map(r=>real?r.slice(0,8):r),V:V.map(r=>real?r.slice(0,8):r)},null,2);}
async function gpuCosines(U,V){if(!gpu)return U.map(u=>V.map(v=>dot(u,v)));const device=gpu,d=U[0].length;const shader=device.createShaderModule({code:`@group(0) @binding(0) var<storage,read> u:array<f32>; @group(0) @binding(1) var<storage,read> v:array<f32>; @group(0) @binding(2) var<storage,read_write> c:array<f32>; @compute @workgroup_size(9) fn main(@builtin(global_invocation_id) id:vec3<u32>){let k=id.x;if(k>=9u){return;}let i=k/3u;let j=k%3u;var s=0.0;for(var t=0u;t<${d}u;t++){s+=u[i*${d}u+t]*v[j*${d}u+t];}c[k]=s;}`});
const input=a=>{const f=new Float32Array(a.flat()),b=device.createBuffer({size:f.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(b,0,f);return b;},ub=input(U),vb=input(V),out=device.createBuffer({size:36,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC}),read=device.createBuffer({size:36,usage:GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST});
try{const pipe=device.createComputePipeline({layout:'auto',compute:{module:shader,entryPoint:'main'}}),group=device.createBindGroup({layout:pipe.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:ub}},{binding:1,resource:{buffer:vb}},{binding:2,resource:{buffer:out}}]});const enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(pipe);pass.setBindGroup(0,group);pass.dispatchWorkgroups(1);pass.end();enc.copyBufferToBuffer(out,0,read,0,36);device.queue.submit([enc.finish()]);await read.mapAsync(GPUMapMode.READ);const result=Array.from(new Float32Array(read.getMappedRange().slice(0)));read.unmap();return [result.slice(0,3),result.slice(3,6),result.slice(6,9)];}finally{[ub,vb,out,read].forEach(b=>b.destroy());}}
async function useToy(){if($('load').disabled)cancelLoad();real=false;U=toyU;V=toyV;stage=0;i=0;j=0;axis='row';$('alpha').value=2;$('toy').setAttribute('aria-pressed',true);$('real').setAttribute('aria-pressed',false);$('live-options').hidden=true;$('provenance').textContent='ILLUSTRATIVE 2D WORKSHEET · chosen vectors, not image embeddings';C=await gpuCosines(U,V);$('runtime').textContent=`Dot products: ${runtime}. Softmax and loss: JavaScript CPU.`;render();}
$('toy').onclick=useToy;$('real').onclick=()=>{ $('live-options').hidden=false;$('real').setAttribute('aria-pressed',true);$('toy').setAttribute('aria-pressed',false);if(live){real=true;U=live.U;V=live.V;C=U.map(u=>V.map(v=>dot(u,v)));$('alpha').value=100;$('provenance').textContent='MEASURED PRETRAINED CLIP · 512D unit vectors · supplied breed captions';$('runtime').textContent=`Live inference: ${live.device} · ${live.dtype}. Display scale α = 100 is a chosen inference setting.`;render();}else $('runtime').textContent='The worksheet remains illustrative until CLIP finishes loading.';};
$('load').onclick=()=>{if(!worker){worker=new Worker('learn-worker.js',{type:'module'});worker.onmessage=({data:m})=>{if(m.type==='status')$('runtime').textContent=m.text;if(m.type==='ready'){live=m;$('load').disabled=false;$('cancel-load').hidden=true;$('match').disabled=false;$('real').click();}if(m.type==='match'){$('extra-score').textContent=`“${m.text}” · cosine ${m.cosine.toFixed(6)} against image 1`;$('match').disabled=false;}if(m.type==='error'){$('error').hidden=false;$('error').textContent=m.text;$('load').disabled=false;$('cancel-load').hidden=true;$('match').disabled=true;}};worker.onerror=e=>{$('error').hidden=false;$('error').textContent=e.message;$('load').disabled=false;$('cancel-load').hidden=true;};}$('error').hidden=true;$('load').disabled=true;$('match').disabled=true;$('cancel-load').hidden=false;worker.postMessage({type:'load',backend:$('backend').value});};
function cancelLoad(){worker?.terminate();worker=null;$('load').disabled=false;$('match').disabled=true;$('cancel-load').hidden=true;$('runtime').textContent='Download cancelled. Choose WebAssembly for the smaller model, or load again.';}
$('cancel-load').onclick=cancelLoad;
$('match').onclick=()=>{const text=$('extra-prompt').value.trim();if(!text){$('extra-score').textContent='Enter a description first.';return;}$('match').disabled=true;worker.postMessage({type:'match',text,image:live.U[0]});};
$('row').onclick=()=>{axis='row';render();};$('col').onclick=()=>{axis='col';render();};$('stage').onchange=()=>{stage=+$('stage').value;render();};$('next').onclick=()=>{stage=Math.min(6,stage+1);render();};$('previous').onclick=()=>{stage=Math.max(0,stage-1);render();};$('alpha').oninput=render;$('reset').onclick=useToy;
try{if(navigator.gpu){const adapter=await navigator.gpu.requestAdapter();if(adapter){gpu=await adapter.requestDevice();runtime='WebGPU compute';gpu.lost.then(()=>{gpu=null;runtime='JavaScript CPU (WebGPU device lost)';if(!real)useToy();});}}}catch(e){runtime='JavaScript CPU (WebGPU unavailable)';}
await useToy();window.clipSimple={calculate,getState:()=>({U,V,C,axis,i,j,stage,real,runtime,live:live?{device:live.device,dtype:live.dtype}:null}),gpuCosines};
addEventListener('pagehide',()=>{worker?.terminate();gpu?.destroy();});
