import json
from pathlib import Path
p=Path('data/experiments.json');x=json.loads(p.read_text())
x.extend([
 dict(id='sustainability',title='Search an overhead landscape',short='Sustainability',mode='classify',image='kiln',candidates=['an aerial image of a brick kiln','an aerial image of a solar farm','an aerial image of agricultural fields','an aerial image of industrial warehouses'],question='What would a sustainability researcher want to retrieve?',lesson='The search idea transfers to satellite tiles, but synthetic images are not evidence of field performance. Real deployment needs georeferenced imagery, independent labels, and evaluation across regions and resolutions.'),
 dict(id='healthcare',title='Recognize the kind of medical image',short='Healthcare',mode='classify',image='chest-xray',candidates=['a chest X-ray','an X-ray of a hand','a brain MRI scan','a photograph of a person'],question='Does recognizing an imaging modality mean the model can diagnose a disease?',lesson='This public radiograph supports a modality-matching lesson, not diagnosis. General CLIP scores are not clinical evidence; medical tasks need domain-specific validation.'),
 dict(id='sketch',title='Keep the concept; change the style',short='Photo → sketch',mode='classify',image='retriever-sketch',candidates=['a drawing of a dog','a drawing of a cat','a drawing of a horse','a drawing of a fox'],question='Can the model recognize a dog when the texture of a photograph disappears?',lesson='This is a small domain-shift experiment. A success here does not establish robustness to every drawing style.'),
 dict(id='color-change',title='A second subtraction experiment',short='Color change',mode='difference',image='red-mug',second='blue-mug',candidates=['blue','red','cup','hat'],question='Does the embedding difference capture a color change as well as an added object?',lesson='Difference directions depend on images, normalization and wording. They are exploratory measurements, not guaranteed semantic algebra.')])
for z,h in zip(x[-4:],["Compare all four overhead scenes. Try ‘brick kiln’ alone, then a longer description. These scenes are synthetic.","Compare modality descriptions first. Notice how different this image is from an everyday photograph.","Switch between the generated photo and sketch. Replace ‘a drawing of’ with ‘a photo of’ and compare.","Reverse the pair. Try ‘a blue mug’ and ‘a red mug’ instead of single words."]):z['try']=h
sources={'hat':('CodeEmporium · hat experiment, 7:25','https://www.youtube.com/watch?v=FCDKn-vpn_o&t=445s'),'color-change':('Extension of the CodeEmporium subtraction idea','https://www.youtube.com/watch?v=FCDKn-vpn_o&t=445s'),'search':('Supabase · image search, 6:54','https://www.youtube.com/watch?v=S7VZErcTN5Y&t=414s'),'neighbors':('Roboflow · embedding analysis, 10:40 and 17:22','https://www.youtube.com/watch?v=YxJkE6FvGF4&t=640s')}
for z in x:z['sourceLabel'],z['sourceURL']=sources.get(z['id'],('CLIP · Radford et al., ICML 2021','https://proceedings.mlr.press/v139/radford21a.html'))
p.write_text(json.dumps(x,indent=2))
