from pathlib import Path
import json,hashlib,html
R=Path(__file__).resolve().parents[1]
gallery=json.loads((R/'data/gallery.json').read_text())
sources=[
('Radford et al., ICML 2021','https://proceedings.mlr.press/v139/radford21a.html','Primary source for the encoders, bidirectional contrastive loss, prompt-based transfer and reported benchmarks. Original training data: 400 million pairs. The lecture’s small experiments are not replications of its benchmarks.'),
('OpenAI CLIP implementation','https://github.com/openai/CLIP/tree/d05afc436d78f1c48dc0dbf8e5980a9d471f35f6','Original weights and Python implementation used in the notebook; MIT. The browser uses the Xenova ONNX conversion of ViT-B/32, revision d15189d7028b43f1d3e65039190477f6af591c2a, with q8 weights.'),
('CodeEmporium — CLIP Explained!','https://www.youtube.com/watch?v=FCDKn-vpn_o&t=445s','At 7:25: compare a portrait with and without a hat by subtracting normalized image embeddings and comparing the difference with word embeddings. This is the source of our hat experiment idea. No creator photographs or slide artwork are used. Our generated pairs and chimney, device, colour and style extensions are separately labelled. We show raw cosine; the reference notebook’s optional scale of 10 is a display choice, not proof of a probability.'),
('Computerphile — How AI Understands Images','https://www.youtube.com/watch?v=KcSXcpluDe4','Around 1:28–4:00: fixed categories versus descriptions and a shared representation. Around 13:15–15:50: downstream zero-shot matching. We adopt the motivation-first teaching pattern, not the video’s artwork.'),
('Yannic Kilcher — OpenAI CLIP paper explanation','https://www.youtube.com/watch?v=T9XSU0pKX2E','Around 4:40–8:00 and 14:40–19:20: image/text pairs, the representation-learning goal and matching within a batch. This informs our gradual move from a retrieval task to a score matrix.'),
('Data Science Gems — OpenAI CLIP','https://www.youtube.com/watch?v=rdMnjvjSAkQ','Around 8:38–12:00: zero-shot classification and wording ambiguity. Around 27:38: examples across visual domains. We use this to motivate testing domains and prompts, while checking technical claims against the paper.'),
('Supabase — Image Search in Python with OpenAI CLIP','https://www.youtube.com/watch?v=S7VZErcTN5Y&t=414s','Around 6:54–11:10: query a gallery using text; a nearest result can still be irrelevant. Our small browser gallery uses direct dot products instead of a database. Search workflow also documented in the linked Supabase tutorial.'),
('Roboflow — CLIP, T-SNE, and UMAP','https://www.youtube.com/watch?v=YxJkE6FvGF4&t=640s','From 10:40: image embeddings for dataset exploration; from 17:22: similarity and possible duplicates. Our app implements nearest-image inspection. It does not claim that similar embeddings prove duplication, or that a 2D projection preserves all distances.')]
photo_sources={
 'newfoundland_31.jpg':('https://www.robots.ox.ac.uk/~vgg/data/pets/','Oxford-IIIT Pet, original image owners; Parkhi, Vedaldi, Zisserman and Jawahar. Distributed via timm/oxford-iiit-pet, revision 089695c834a7deb60505b7cc506672db1c31a6aa. CC BY-SA 4.0. Same bytes as Vision I.'),
 'Persian_98.jpg':('https://www.robots.ox.ac.uk/~vgg/data/pets/','Oxford-IIIT Pet, original image owners; Parkhi et al. CC BY-SA 4.0. Same bytes as Vision I.'),
 'pug_57.jpg':('https://www.robots.ox.ac.uk/~vgg/data/pets/','Oxford-IIIT Pet, original image owners; Parkhi et al. CC BY-SA 4.0. Same bytes as Vision I.'),
 'coffee.jpg':('https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.coffee','Rachel Michetti, courtesy of Pikolo Espresso Bar. CC0. Exported from scikit-image data, JPEG quality 95.'),
 'chelsea.jpg':('https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.chelsea','Stefan van der Walt. CC0. Exported from scikit-image data, JPEG quality 95.'),
 'rocket.jpg':('https://www.flickr.com/photos/spacexphotos/16511594820/','SpaceX DSCOVR launch. Public domain, via scikit-image data; exported JPEG quality 95.'),
 'astronaut.jpg':('https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.astronaut','NASA photograph of Eileen Collins. Public domain, via scikit-image data; exported JPEG quality 95.'),
 'chest-xray.png':('https://commons.wikimedia.org/wiki/File:Chest_Xray_PA_3-8-2010.png','Stillwaterising, Wikimedia Commons, CC0 1.0. Public chest radiograph; no diagnostic label is inferred by this lab.')}
manifest=[]
for file in sorted(set(g['file'] for g in gallery)):
 p=R/'images'/file;source,credit=photo_sources.get(file,('generated-prompts.md','Generated for this lesson with the built-in OpenAI image tool on 29 September 2026. Synthetic, not a real person, site survey or patient. See the prompt record.'))
 manifest.append(dict(file=file,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),source=source,credit=credit))
(R/'images/provenance.json').write_text(json.dumps(manifest,indent=2))
e=html.escape
body='<h1>Sources & credits</h1><p>This lab teaches existing ideas with newly written exercises and code. Source ideas, public photographs, generated pictures and measured results are distinguished below.</p><h2>Ideas and teaching references</h2><p>Review method: public captions and targeted timestamped sections, plus the primary paper and code. We do not claim uninterrupted audiovisual viewing. Full transcripts and third-party notebooks are not redistributed.</p><ul>'+''.join(f'<li><a href="{e(u)}">{e(t)}</a><br>{e(d)}</li>' for t,u,d in sources)+'</ul><h2>Image provenance</h2><ul>'+''.join(f'<li><a href="{e(x["source"])}">{e(x["file"])}</a> — {e(x["credit"])}</li>' for x in manifest)+'</ul><p>Paired panels are cropped at their midpoint during model preprocessing and displayed separately. The original generated images are preserved. Generated medical anatomy and device placement are approximate and are not clinical evidence. Synthetic remote-sensing scenes have no real coordinates or measured ground resolution.</p><h2>What was actually run?</h2><p>OpenAI CLIP ViT-B/32 in the executed notebook; a pinned q8 ONNX conversion in the live browser and recorded CPU runs. Recorded measurements are explicitly labelled. Browser canvas and Python/PIL or Node image resizing can yield small score differences.</p><p>The separate tiny training experiment uses 270 generated geometric images for training and 90 held-out images, with both encoders initialized randomly. Its architecture and dataset differ from CLIP; it demonstrates the loss learning a shared space, not healthcare or satellite accuracy.</p><p><a href="data/evidence.json">Recorded CPU measurements</a> · <a href="data/browser-evidence.json">Browser measurements</a> · <a href="images/provenance.json">Image checksums</a> · <a href="generated-prompts.md">Generation prompts</a></p>'
(R/'sources.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CLIP Lab — Sources and credits</title><link rel="stylesheet" href="style.css"><body><header class="top"><a class="brand" href="index.html">CLIP LAB</a><a href="training.html">Before / after training</a></header><main class="document">'+body+'</main></body></html>')
(R/'SOURCES.md').write_text('# Sources and attribution\n\n'+ '\n\n'.join(f'- [{t}]({u}): {d}' for t,u,d in sources)+'\n\nImage licenses, creators and checksums: [provenance.json](images/provenance.json). Generation record: [generated-prompts.md](generated-prompts.md).\n')
