const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const puppeteer=require(process.env.CLIP_PUPPETEER_PATH||'/Users/nipun/git/dl-teaching/node_modules/puppeteer');
const out=path.resolve('output/verification/playground');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await puppeteer.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=metal'],userDataDir:path.resolve(process.env.CLIP_BROWSER_PROFILE||'work/playground-browser')});try{
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1440,height:1100});await p.goto((process.env.CLIP_TEST_URL||'http://127.0.0.1:5190')+'/playground/');await p.waitForFunction(()=>window.clipPlayground);await p.screenshot({path:out+'/initial.png',fullPage:true});
 assert.equal(await p.$eval('#question-select',n=>n.options.length),11);
 for(const id of ['negation','hat','search','colour','menu','first']){await p.select('#question-select',id);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await p.select('#question-select','hat');await p.click('#swap');assert.equal(await p.evaluate(()=>clipPlayground.getState().image),'portrait-hat');
 // Warm the browser cache from the exact pinned local files. Inference still executes on this browser's WebGPU/CPU.
 if(!process.env.CLIP_COLD_DOWNLOAD)await p.evaluate(async backend=>{const rev='d15189d7028b43f1d3e65039190477f6af591c2a',base='https://huggingface.co/Xenova/clip-vit-base-patch32/resolve/'+rev+'/',cache=await caches.open('transformers-cache');const files=['tokenizer.json','tokenizer_config.json','preprocessor_config.json','config.json',...(backend==='wasm'?['onnx/text_model_quantized.onnx','onnx/vision_model_quantized.onnx']:['onnx/text_model.onnx','onnx/vision_model.onnx'])];for(const f of files){const response=await fetch('/.cache/Xenova/clip-vit-base-patch32/'+rev+'/'+f);if(!response.ok)throw Error('Missing cache: '+f);await cache.put(base+f,response);}},process.env.CLIP_TEST_BACKEND||'auto');
 await p.select('#question-select','first');await p.select('#backend',process.env.CLIP_TEST_BACKEND||'auto');await p.click('#run');
 let last='';for(let i=0;i<180;i++){await new Promise(r=>setTimeout(r,2000));const status=await p.$eval('#runtime-status',n=>n.textContent);if(status!==last){console.log(status);last=status;}const error=await p.$eval('#error',n=>n.hidden?'':n.textContent);if(error)throw Error(error);if(await p.evaluate(()=>Boolean(clipPlayground.getState().result)))break;}
 const first=await p.evaluate(()=>clipPlayground.getState().result);assert(first,'Inference timed out');assert.equal(first.vectors.length,4);first.vectors.forEach(v=>{assert.equal(v.unit.length,512);assert(Math.abs(Math.hypot(...v.unit)-1)<1e-6);assert(v.raw.every(Number.isFinite));});
 console.log('First inference:',JSON.stringify({device:first.device,dtype:first.dtype,scores:first.scores}));
 for(let stage=0;stage<3;stage++){await p.click(`[data-stage="${stage}"]`);await p.screenshot({path:out+'/stage-'+stage+'.png',fullPage:true});}
 await p.$eval('#coordinate',n=>{n.value=504;n.dispatchEvent(new Event('input',{bubbles:true}));});assert((await p.$eval('#dot-details',n=>n.textContent)).includes('505'));
 await p.click('.temperature summary');await p.$eval('#temperature',n=>{n.value=1;n.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await p.$eval('#tau-label',n=>n.textContent),'1.00');assert.deepEqual(await p.evaluate(()=>clipPlayground.getState().result.scores),first.scores);
 await p.$eval('#descriptions',n=>{n.value+='\na tabby cat';n.dispatchEvent(new Event('input',{bubbles:true}));});assert(!(await p.$eval('#stale',n=>n.hidden)));await p.click('#run');await p.waitForFunction(()=>!clipPlayground.getState().busy,{timeout:120000});const extra=await p.evaluate(()=>clipPlayground.getState().result);assert.equal(extra.scores.length,4);assert.deepEqual(extra.vectors[0].unit,first.vectors[0].unit);
 async function preset(id){await p.select('#question-select',id);await p.click('#run');await p.waitForFunction(()=>!clipPlayground.getState().busy,{timeout:180000});const error=await p.$eval('#error',n=>n.hidden?'':n.textContent);if(error)throw Error(error);return p.evaluate(()=>clipPlayground.getState().result);}
 const hat=await preset('hat');await p.click('#swap');await p.click('#run');await p.waitForFunction(()=>!clipPlayground.getState().busy,{timeout:120000});const reverse=await p.evaluate(()=>clipPlayground.getState().result);for(const s of hat.scores){assert(Math.abs(s.cosine+reverse.scores.find(r=>r.label===s.label).cosine)<1e-7);}
 const search=await preset('search');assert.equal(search.scores.length,22);await p.click('[data-stage="2"]');await p.screenshot({path:out+'/search.png',fullPage:true});
 await p.setViewport({width:390,height:844});for(let stage=0;stage<3;stage++){await p.click(`[data-stage="${stage}"]`);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow stage '+stage);await p.screenshot({path:out+'/mobile-'+stage+'.png',fullPage:true});}
 await p.setViewport({width:1440,height:1000});await p.select('#question-select','hat');await p.click('[data-mode="match"]');await p.$eval('#descriptions',n=>n.value='');await p.click('#run');assert((await p.$eval('#error',n=>n.textContent)).includes('at least one'));
 const file=await p.$('#upload');await file.uploadFile(path.resolve('images/coffee.jpg'));await p.waitForFunction(()=>clipPlayground.getState().image.startsWith('upload-'));await p.$eval('#descriptions',n=>n.value='a cup of coffee\na dog');await p.click('#run');await p.waitForFunction(()=>!clipPlayground.getState().busy,{timeout:120000});const upload=await p.evaluate(()=>clipPlayground.getState().result);assert(upload.vectors.some(v=>v.imageId?.startsWith('upload-')));assert.equal(upload.scores[0].label,'a cup of coffee');
 assert.deepEqual(errors,[]);const report={passed:true,device:first.device,dtype:first.dtype,modelDelivery:process.env.CLIP_COLD_DOWNLOAD?'Hugging Face network':'Pinned local weights placed in browser cache',firstScores:first.scores,searchTop:search.scores.slice(0,3),changeSignReversal:true,unitVectors:true,customDescription:true,localUpload:true,mobileWidth:390,errors};fs.writeFileSync(out+'/report-'+first.device+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
