export const questions=[
 {id:'first',name:'01 · Let the words choose the class',mode:'match',image:'chelsea',texts:['a photo of a cat','a photo of a dog','a photo of a rocket'],question:'Which description will be closest to this photograph?',try:'Run it once. Then replace “cat” with “tabby cat” and compare the scores.',notice:'CLIP computes a new vector for each description. Writing a new label does not retrain the model.'},
 {id:'breed',name:'02 · A dog, or a particular kind of dog?',mode:'match',image:'pug',texts:['a photo of a dog','a photo of a pug','a photo of a Newfoundland','a photo of a Persian cat'],question:'Will a more specific description help?',try:'Predict the ranking before running. Try “a small dog with a wrinkled face”.',notice:'Specificity can help, but adding words does not guarantee a higher score. Inspect the actual ranking.'},
 {id:'negation',name:'03 · Does “without” change the match?',mode:'match',image:'Persian',texts:['a photo of a cat','a photo without a cat','a photo of a dog'],question:'How far apart are “a cat” and “without a cat”?',try:'Compare their cosines. Then try “there is no cat in this image”.',notice:'Similar scores here are a limitation, not evidence that negation has been understood. A matching score is not a logical truth value.'},
 {id:'words',name:'04 · Keep the image. Change the wording.',mode:'match',image:'coffee',texts:['coffee','a cup of coffee','a photo of a cup of coffee','a cup of tea','a cup of hot chocolate'],question:'Does the wording change the answer?',try:'Add your own description. The image vector should stay the same.',notice:'Every wording gets its own text vector. An unchanged image keeps the same vector within this loaded runtime.'},
 {id:'search',name:'05 · Find an image without naming its file',mode:'search',query:'something you can drink',question:'Which gallery image would you retrieve for these words?',try:'Try “a journey into space” or “an animal with floppy ears”.',notice:'One text vector is compared with every gallery image vector. All scores are calculated from the loaded model.'},
 {id:'hat',name:'06 · What changed between these images?',mode:'difference',image:'portrait',second:'portrait-hat',texts:['hat','boat','cup','cat'],question:'Can the difference between two image vectors point toward “hat”?',try:'Run the pair, inspect the difference vector, then swap before and after.',notice:'The query is normalize(u_after − u_before). Swapping the order reverses every score. The generated pair may also differ in unintended details; CLIP did not create the edit.'},
 {id:'colour',name:'07 · Can we isolate a colour change?',mode:'difference',image:'red-mug',second:'blue-mug',texts:['blue','red','a handle','a table'],question:'What should have a positive score after red changes to blue?',try:'Compare both signs. Swap the images and run again.',notice:'A signed dot product describes alignment with the change direction. It is not a probability that a word was added or removed.'},
 {id:'style',name:'08 · Does a sketch still look like a dog?',mode:'match',image:'retriever-sketch',texts:['a dog','a pencil sketch of a dog','a photograph of a dog','a pencil sketch of a cat'],question:'Does CLIP notice the animal, the style, or both?',try:'Compare this sketch with the “Dog photograph style” sample in the gallery.',notice:'The candidate descriptions combine content and style. A higher match does not tell us which property caused the difference on its own.'},
 {id:'menu',name:'09 · Can the answer menu make us overconfident?',mode:'match',image:'rocket',texts:['a rocket launching at night','a building','a streetlight'],question:'Does a large softmax share mean the description must be correct?',try:'Run the comparison and open the temperature control. Then remove the rocket description and run again.',notice:'The shares add to one over only the supplied descriptions. An incomplete menu still has a winner. Changing temperature changes shares, not the cosine ranking.'},
 {id:'domain',name:'10 · Try a different kind of image',mode:'match',image:'solar',texts:['an aerial image of a solar farm','an aerial image of agricultural fields','an aerial image of warehouses','an aerial image of a brick kiln'],question:'Will familiar words transfer to an aerial view?',try:'Choose another aerial sample and keep the descriptions fixed.',notice:'These aerial scenes are generated teaching images. Results illustrate this gallery; they are not a benchmark of satellite imagery.'},
 {id:'own',name:'11 · Design your own test',mode:'match',image:'astronaut',texts:['a portrait of an astronaut','a person wearing a helmet','a rocket in space'],question:'What change would help you test your explanation?',try:'Upload an image or choose a sample. Change one thing at a time: the image, a description, or the answer menu.',notice:'Keep a record of the inputs and runtime with Download vectors. One surprising example suggests a test; it does not establish a general rule.'}
];
